Improve classpath setup in bin/flumebase.
Add 'bin/flumebase classpath' to print the classpath and exit.
Use '$FLUME_HOME/bin/flume classpath' to get Flume's classpath,
rather than tracing down dependencies ourselves.

diff --git a/bin/flumebase b/bin/flumebase
--- a/bin/flumebase
+++ b/bin/flumebase
@@ -16,6 +16,8 @@
 # under the License.
 #
 
+# TODO: Follow symlinks and resolve this back to its full name
+# (e.g., 'readlink -f' -- which is Linux-specific).
 bin=`dirname $0`
 bin=`cd "${bin}" && pwd`
 
@@ -25,40 +27,21 @@ LIB_DIR="${projectroot}/lib"
 MVN_TARGET_DIR="${projectroot}/target"
 MVN_BUILD_DEPS_DIR="${MVN_TARGET_DIR}/dependency"
 
-# CDH installation default
+# CDH installation default for Flume.
 FLUME_HOME=${FLUME_HOME:-/usr/lib/flume}
-ZOOKEEPER_HOME=${ZOOKEEPER_HOME:-/usr/lib/zookeeper}
-
-function usage() {
-  echo "Usage: flumebase <command> [args...]"
-  echo "Commands include:"
-  echo "  shell     Start the FlumeBase shell"
-  echo "  server    Start a server to run background queries"
-  echo "  version   Print FlumeBase version information and exit"
-}
-
-# Format: flumebase <command> [args...]
-action="$1"
-shift
-if [ -z "$action" ]; then
-  usage
-  exit 0
-elif [ "$action" == "shell" ]; then
-  FLUMEBASE_MAIN_CLASS=com.odiago.flumebase.client.CmdLineClient
-elif [ "$action" == "server" ]; then
-  FLUMEBASE_MAIN_CLASS=com.odiago.flumebase.server.ServerMain
-elif [ "$action" == "version" ]; then
-  FLUMEBASE_MAIN_CLASS=com.odiago.flumebase.util.VersionInfo
-else
-  echo "Invalid command: $action"
-  usage
-  exit 1
-fi
-
 
 FLUMEBASE_CLASSPATH="${FLUMEBASE_CLASSPATH:-}"
 FLUMEBASE_OPTS="${FLUMEBASE_OPTS:-}"
 FLUMEBASE_CONF_DIR=${FLUMEBASE_CONF_DIR:-"${projectroot}/etc"}
+
+function usage() {
+  echo "Usage: flumebase <command> [args...]"
+  echo "Commands include:"
+  echo "  classpath   Print the classpath used by Java executables and exit"
+  echo "  shell       Start the FlumeBase shell"
+  echo "  server      Start a server to run background queries"
+  echo "  version     Print FlumeBase version information and exit"
+}
 
 function add_to_classpath() {
   dir=$1
@@ -83,6 +66,12 @@ if [ \( ! -d "${LIB_DIR}" \) -a \( ! -d "${MVN_BUILD_DEPS_DIR}" \) ]; then
     pushd "${projectroot}"
     echo "Retrieving dependencies via mvn"
     mvn dependency:copy-dependencies
+    mvnret=$?
+    if [ "${mvnret}" != 0 ]; then
+      echo "WARNING: It looks like you're running from a development branch, but"
+      echo "I couldn't retrieve dependencies via mvn. If an unmet dependency is"
+      echo "required at runtime, it will probably explode."
+    fi
     popd
   else
     echo "WARNING: Couldn't find any dependencies. mvn doesn't seem to be"
@@ -94,32 +83,45 @@ fi
 add_to_classpath "${MVN_BUILD_DEPS_DIR}"
 add_to_classpath "${LIB_DIR}"
 
-# Put Flume (and via this, Hadoop) directly on the classpath; we don't redistribute
-# Flume with FlumeBase; it's marked as a 'provided' dependency.
-if [ ! -z "${FLUME_HOME}" -a -d "${FLUME_HOME}/lib" ]; then
-  add_to_classpath "${FLUME_HOME}/lib"
+# Get Flume's classpath dependencies from Flume itself, and put Flume (and
+# via this, Hadoop) directly on the classpath; we don't redistribute Flume
+# with FlumeBase; it's marked as a 'provided' dependency.
+if [ -x "${FLUME_HOME}/bin/flume" ]; then
+  flume_classpath=`${FLUME_HOME}/bin/flume classpath`
+  if [ ! -z "${flume_classpath}" ]; then
+    # Add these to our classpath.
+    FLUMEBASE_CLASSPATH="${FLUMEBASE_CLASSPATH}:${flume_classpath}"
+  fi
 else
   echo "Warning: Couldn't find Flume installation. Make sure \$FLUME_HOME is set."
   exit 1
 fi
 
-# Flume depends on Zookeeper, add this too. Source installations of Flume
-# actually bundle zk, so it is not a failure if this is not present.
-if [ ! -z "${ZOOKEEPER_HOME}" -a -d "${ZOOKEEPER_HOME}" ]; then
-  add_to_classpath "${ZOOKEEPER_HOME}"
-fi
-
-# If pulling Flume from a development repository, its jar is in build/, not lib/.
-if [ ! -z "${FLUME_HOME}" -a -d "${FLUME_HOME}/build" ]; then
-  flumejar=`ls -1 ${FLUME_HOME}/build/flume-*-core.jar | head -1`
-  FLUMEBASE_CLASSPATH="${FLUMEBASE_CLASSPATH}:${flumejar}"
-fi
-
-
 if [ -d "${MVN_TARGET_DIR}/classes" ]; then
   # If there's a target/classes/ dir, then we want to put this ahead of any
   # jars on the classpath; use the most recently compiled bits.
   FLUMEBASE_CLASSPATH="${MVN_TARGET_DIR}/classes:$FLUMEBASE_CLASSPATH"
+fi
+
+# Invocation format: flumebase <command> [args...]
+action="$1"
+shift
+if [ -z "$action" ]; then
+  usage
+  exit 0
+elif [ "$action" == "shell" ]; then
+  FLUMEBASE_MAIN_CLASS=com.odiago.flumebase.client.CmdLineClient
+elif [ "$action" == "server" ]; then
+  FLUMEBASE_MAIN_CLASS=com.odiago.flumebase.server.ServerMain
+elif [ "$action" == "version" ]; then
+  FLUMEBASE_MAIN_CLASS=com.odiago.flumebase.util.VersionInfo
+elif [ "$action" == "classpath" ]; then
+  echo "$FLUMEBASE_CLASSPATH"
+  exit 0
+else
+  echo "Invalid command: $action"
+  usage
+  exit 1
 fi
 
 exec java -cp "${FLUMEBASE_CLASSPATH}" \
