Add 'start', 'stop' commands to bin/flumebase
Can start/stop server instances in the background.
Uses pid files to ensure at most one server starts.
Writes log output to DRFA in a log directory.
Uses FLUMEBASE_PID_DIR, FLUMEBASE_LOG_DIR to control locations.

Environment variables are controlled by etc/flumebase-env.sh
bin/flumebase now follows symlinks to its true home directory.
ServerMain acquires PidFile instance.
LocalEnvironment now uses a shutdown hook to force cleanup on the way out.

diff --git a/bin/flumebase b/bin/flumebase
--- a/bin/flumebase
+++ b/bin/flumebase
@@ -16,29 +16,111 @@
 # under the License.
 #
 
-# TODO: Follow symlinks and resolve this back to its full name
-# (e.g., 'readlink -f' -- which is Linux-specific).
-bin=`dirname $0`
-bin=`cd "${bin}" && pwd`
+follow_one() {
+  # Resolve symlinks and relative path components along a path.  This requires
+  # its argument to be an absolute path.  This does not recursively re-resolve
+  # symlinks; if that is required, use the 'follow' method.
+
+  target=$1
+  OIFS=$IFS
+  IFS='/'
+
+  # Taking each dir component along the way, build up a new target directory,
+  # resolving '.', '..', and symlinks.
+  newtarget=''
+  for part in ${target}; do
+    if [ -z "${part}" ]; then
+      continue # Empty dir part. 'foo//bar'
+    elif [ "." == "${part}" ]; then
+      continue # Nothing special to do for '.'
+    elif  [ ".." == "${part}" ]; then
+      IFS=$OIFS
+      newtarget=`dirname ${newtarget}` # pop a component.
+    elif [ -h "${newtarget}/${part}" ]; then
+      IFS=$OIFS
+      link=`readlink ${newtarget}/${part}`
+      # links can be relative or absolute. Relative ones get appended to
+      # newtarget; absolute ones replace it.
+      if [ "${link:0:1}" != "/"  ]; then
+        newtarget="${newtarget}/${link}" # relative
+      else
+        newtarget="${link}" # absolute
+      fi
+    else # Regular file component.
+      newtarget="${newtarget}/${part}"
+    fi
+    IFS='/'
+  done
+
+  IFS=$OIFS
+  echo $newtarget
+}
+
+follow() {
+  # Portable 'readlink -f' function to follow a file's links to the final
+  # target.  Calls follow_one recursively til we're finished tracing symlinks.
+
+  target=$1
+  depth=$2
+
+  if [ -z "$depth" ]; then
+    depth=0
+  elif [ "$depth" == "1000" ]; then
+    # Don't recurse indefinitely; we've probably hit a symlink cycle.
+    # Just bail out here.
+    echo $target
+    return 1
+  fi
+
+  # Canonicalize the target to be an absolute path.
+  targetdir=`dirname ${target}`
+  targetdir=`cd ${targetdir} && pwd`
+  target=${targetdir}/`basename ${target}`
+
+  # Use follow_one to resolve links. Test that we get the same result twice,
+  # to terminate iteration.
+  first=`follow_one ${target}`
+  second=`follow_one ${first}`
+  if [ "${first}" == "${second}" ]; then
+    # We're done.
+    echo "${second}"
+  else
+    # Need to continue resolving links.
+    echo `follow ${second} $(( $depth + 1 ))`
+  fi
+}
+
+# Resolve bin directory recursively following symlinks, etc.
+prgm=`follow $0`
+bin=`dirname ${prgm}`
+bin=`cd ${bin} && pwd`
 
 projectroot=`cd "${bin}/.." && pwd`
 
-LIB_DIR="${projectroot}/lib"
 MVN_TARGET_DIR="${projectroot}/target"
 MVN_BUILD_DEPS_DIR="${MVN_TARGET_DIR}/dependency"
 
-# CDH installation default for Flume.
-FLUME_HOME=${FLUME_HOME:-/usr/lib/flume}
+export FLUMEBASE_HOME=${FLUMEBASE_HOME:-${projectroot}}
+export FLUMEBASE_CONF_DIR=${FLUMEBASE_CONF_DIR:-"${FLUMEBASE_HOME}/etc"}
 
-FLUMEBASE_CLASSPATH="${FLUMEBASE_CLASSPATH:-}"
-FLUMEBASE_OPTS="${FLUMEBASE_OPTS:-}"
-FLUMEBASE_CONF_DIR=${FLUMEBASE_CONF_DIR:-"${projectroot}/etc"}
+if [ ! -f ${FLUMEBASE_CONF_DIR}/flumebase-env.sh ]; then
+  echo "Could not find flumebase-env.sh"
+  echo "Make sure \$FLUMEBASE_HOME or \$FLUMEBASE_CONF_DIR is set correctly."
+  exit 1
+fi
+
+source ${FLUMEBASE_CONF_DIR}/flumebase-env.sh
+
+LIB_DIR="${FLUMEBASE_HOME}/lib"
 
 function usage() {
   echo "Usage: flumebase <command> [args...]"
   echo "Commands include:"
   echo "  shell       Start the FlumeBase shell"
-  echo "  server      Start a server to run persistent queries"
+  echo ""
+  echo "  start       Start a daemon server to run persistent queries"
+  echo "  server      Start a server as a foreground process"
+  echo "  stop        Stop a running server"
   echo ""
   echo "  classpath   Print the classpath used by Java executables and exit"
   echo "  version     Print FlumeBase version information and exit"
@@ -57,6 +139,20 @@ function add_to_classpath() {
     fi
   done
 }
+
+function create_missing_dir() {
+  dirname=$1
+
+  # Create the directory identified if it does not exist already.
+  if [ ! -z "$dirname" -a ! -d "$dirname" ]; then
+    if [ -e "$dirname" ]; then
+      echo "Warning: $dirname exists but is not a directory"
+      return 1
+    fi
+    mkdir -p $dirname
+  fi
+}
+
 
 # If no lib dir exists and no dependency dir exists, then
 # try to use mvn to retrieve dependencies.
@@ -104,6 +200,10 @@ if [ -d "${MVN_TARGET_DIR}/classes" ]; then
   FLUMEBASE_CLASSPATH="${MVN_TARGET_DIR}/classes:$FLUMEBASE_CLASSPATH"
 fi
 
+export FLUMEBASE_CLASSPATH
+
+foreground=true
+
 # Invocation format: flumebase <command> [args...]
 action="$1"
 shift
@@ -113,9 +213,54 @@ if [ -z "$action" ]; then
 elif [ "$action" == "shell" ]; then
   FLUMEBASE_MAIN_CLASS=com.odiago.flumebase.client.CmdLineClient
 elif [ "$action" == "server" ]; then
+  create_missing_dir $FLUMEBASE_PID_DIR
   FLUMEBASE_MAIN_CLASS=com.odiago.flumebase.server.ServerMain
 elif [ "$action" == "version" ]; then
   FLUMEBASE_MAIN_CLASS=com.odiago.flumebase.util.VersionInfo
+elif [ "$action" == "start" ]; then
+  FLUMEBASE_MAIN_CLASS=com.odiago.flumebase.server.ServerMain
+  create_missing_dir $FLUMEBASE_LOG_DIR
+  create_missing_dir $FLUMEBASE_PID_DIR
+  foreground=false
+  export FLUMEBASE_OPTS="-Dlog4j.rootLogger=INFO,drfa \
+-Dflumebase.log.dir=$FLUMEBASE_LOG_DIR $FLUMEBASE_OPTS"
+elif [ "$action" == "stop" ]; then
+  if [ ! -f "$FLUMEBASE_PID_DIR/flumebase.pid" ]; then
+    echo "Cannot find pid file. No FlumeBase instance running?"
+    exit 1
+  fi
+  PID=`cat $FLUMEBASE_PID_DIR/flumebase.pid`
+  if [ -z "$PID" ]; then
+    echo "No PID in pid file? Cannot stop server."
+    exit 1
+  fi
+  echo "Stopping server..."
+  kill $PID
+  ret=$?
+  if [ "$ret" != "0" ]; then
+    echo "Error killing process with pid $PID"
+    exit 1
+  fi
+  echo "Waiting for shutdown..."
+  tries=5
+  while [ "$tries" -gt 0 ]; do
+    tries=$(($tries - 1))
+    ps ef | grep "^$PID" 2>&1 > /dev/null
+    ret=$?
+    if [ "$ret" != 0 ]; then
+      break
+    fi
+    sleep 2
+  done
+  ps ef | grep "^$PID" 2>&1 > /dev/null
+  ret=$?
+  if [ "$ret" == 0 ]; then
+    echo "Kill signal sent but server did not shut down within timeout."
+    exit 1
+  fi
+  # FlumeBase will delete its own pid file.
+  echo "FlumeBase server shutdown."
+  exit 0
 elif [ "$action" == "classpath" ]; then
   echo "$FLUMEBASE_CLASSPATH"
   exit 0
@@ -125,8 +270,17 @@ else
   exit 1
 fi
 
-exec java -cp "${FLUMEBASE_CLASSPATH}" \
-    -Dflumebase.conf.dir="${FLUMEBASE_CONF_DIR}" \
-    $FLUMEBASE_OPTS \
-    "${FLUMEBASE_MAIN_CLASS}" "$@"
+if $foreground ; then
+  exec java -cp "${FLUMEBASE_CLASSPATH}" \
+      -Dflumebase.conf.dir="${FLUMEBASE_CONF_DIR}" \
+      -Xmx${FLUMEBASE_HEAP_SIZE}m \
+      $FLUMEBASE_OPTS \
+      "${FLUMEBASE_MAIN_CLASS}" "$@"
+else      
+  nohup java -cp "${FLUMEBASE_CLASSPATH}" \
+      -Dflumebase.conf.dir="${FLUMEBASE_CONF_DIR}" \
+      -Xmx${FLUMEBASE_HEAP_SIZE}m \
+      $FLUMEBASE_OPTS \
+      "${FLUMEBASE_MAIN_CLASS}" "$@" >/dev/null 2>&1 </dev/null &
+fi
 
