Use thrift to proxy requests to a remote LocalEnv.
Created an initial remote server implementation running the LocalEnvironment
internally.
Added a thrift interface between remote server and the client.
Added RemoteServerImpl, the implementation of the remote server.
Added ThriftClientEnvironment, an ExecEnv implementation that invokes thrift
calls to the remote server.
Added ServerMain, which contains main() for the remote server.
Added DummyExecEnv which is a minimalist implementation of ExecEnv.
CmdLineClient can now disconnect from an environment and connect to a new one.
Added shutdown() to the ExecEnv API.
Factored out common startup methods from CmdLineClient, ServerMain into
AppUtils.
Renamed bin/rtshell to rtsql; requires argument to determine whether it starts
a client or a server.

diff --git a/bin/rtsql b/bin/rtsql
--- a/bin/rtsql
+++ b/bin/rtsql
@@ -9,7 +9,29 @@ LIB_DIR="${projectroot}/lib"
 MVN_TARGET_DIR="${projectroot}/target"
 MVN_BUILD_DEPS_DIR="${MVN_TARGET_DIR}/dependency"
 
-RTENGINE_MAIN_CLASS=com.odiago.rtengine.client.CmdLineClient
+function usage() {
+  echo "Usage: rtsql <command> [args...]"
+  echo "Commands include:"
+  echo "  shell     Start the rtsql shell"
+  echo "  server    Start a server to run background queries"
+}
+
+# Format: rtsql <command> [args...]
+action="$1"
+shift
+if [ -z "$action" ]; then
+  usage
+  exit 0
+elif [ "$action" == "shell" ]; then
+  RTENGINE_MAIN_CLASS=com.odiago.rtengine.client.CmdLineClient
+elif [ "$action" == "server" ]; then
+  RTENGINE_MAIN_CLASS=com.odiago.rtengine.server.ServerMain
+else
+  echo "Invalid command: $action"
+  usage
+  exit 1
+fi
+
 
 RTENGINE_CLASSPATH="${RTENGINE_CLASSPATH:-}"
 RTENGINE_OPTS="${RTENGINE_OPTS:-}"
